environment:
    scramble_moves: 10

DQN:
    cross:
        mem_capacity: 100000
        gamma: 0.8
        batch_size: 4096
        eps_start: 0.4
        eps_end: 0.01
        eps_decay: 4000
        tau: 0.005
        lr: 3e-5
        num_episodes: 600
    f2l:
        mem_capacity: 100000
        gamma: 0.4
        batch_size: 4096
        eps_start: 0.4
        eps_end: 0.01
        eps_decay: 3000
        tau: 0.005
        lr: 3e-5
        num_episodes: 600


PPO:
    cross:
        total_timesteps: 200000000
        timesteps_per_batch: 8192
        max_timesteps_per_episode: 4096
        gamma: 0.6
        lr: 0.005
        n_updates_per_iteration: 5
        clip: 0.2
    f2l:
        total_timesteps: 200000000
        timesteps_per_batch: 4096
        max_timesteps_per_episode: 4096
        gamma: 0.6
        lr: 0.005
        n_updates_per_iteration: 5
        clip: 0.2

SA2C:
    alpha: 0.0003
    beta: 0.0003
    gamma: 0.99
    n_actions: 19
    max_size: 1000000
    tau: 0.005
    batch_size: 256
    reward_scale: 2
