environment:
    scramble_moves: 10

DQN:
    mem_capacity: 100000
    gamma: 0.4
    batch_size: 2048
    eps_start: 0.9
    eps_end: 0.01
    eps_decay: 5000
    tau: 0.005
    lr: 3e-5
    n_actions: 19
    num_episodes: 10000

SA2C:
    alpha: 0.0003
    beta: 0.0003
    gamma: 0.99
    n_actions: 19
    max_size: 1000000
    tau: 0.005
    batch_size: 256
    reward_scale: 2