# Training hyperparameters
num_episodes: 600

# Algorithms settings
DQN:
    mem_capacity: 10000
    gamma: 0.99
    batch_size: 128
    eps_start: 0.09
    eps_end: 0.01
    eps_decay: 2500
    tau: 0.005
    lr: 3e-4
    n_actions: 12

A2C: