environment:
    scramble_moves: 10

DQN:
    mem_capacity: 100000
    gamma: 0.4
    batch_size: 4096
    eps_start: 0.9
    eps_end: 0.01
    eps_decay: 5000
    tau: 0.005
    lr: 3e-5
    num_episodes: 600

PPO:
    total_timesteps: 10
    timesteps_per_batch: 4800
    max_timesteps_per_episode: 1600

SA2C:
    alpha: 0.0003
    beta: 0.0003
    gamma: 0.99
    n_actions: 19
    max_size: 1000000
    tau: 0.005
    batch_size: 256
    reward_scale: 2
