DQN:
    mem_capacity: 4294967296
    gamma: 0.7
    batch_size: 1048576
    eps_start: 0.9
    eps_end: 0.01
    eps_decay: 2500
    tau: 0.005
    lr: 3e-4
    n_actions: 12
    num_episodes: 600

A2C: